"""Round-trip test against real sengol-signed fixtures.

Fixtures are generated by ``scripts/generate_fixture.py`` running against
the real sengol package (see that script's docstring) and committed under
``tests/fixtures/`` so this test needs no sengol installation to run.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sengol_verify.verify import verify_bundle_file

_FIXTURES = Path(__file__).parent / "fixtures"


def test_genuine_bundle_verifies_unverifiable_only_on_withheld_hmac():
    """A real export never ships HMAC key material (withheld by design), so
    the honest verdict is UNVERIFIABLE on that ONE step — every other step,
    including the Ed25519 countersignatures, is a clean PASS.
    """
    result = verify_bundle_file(_FIXTURES / "bundle.json")
    by_check = {s.check: s for s in result.step_results}
    assert by_check["hmac_verify"].result == "UNVERIFIABLE"
    for check in (
        "payload_hash_integrity",
        "chain_continuity",
        "ed25519_countersig",
        "anchor_coverage",
        "field_coverage",
    ):
        assert by_check[check].result == "PASS", (check, by_check[check].detail)
    assert result.verdict == "UNVERIFIABLE"


def test_bundle_with_hmac_material_verifies_full_pass():
    result = verify_bundle_file(_FIXTURES / "bundle_full_pass.json")
    assert result.verdict == "PASS", [(s.check, s.result, s.detail) for s in result.step_results]


def test_genuine_bundle_as_directory(tmp_path):
    (tmp_path / "bundle.json").write_text((_FIXTURES / "bundle_full_pass.json").read_text())
    result = verify_bundle_file(tmp_path)
    assert result.verdict == "PASS"


def test_genuine_bundle_as_zip(tmp_path):
    import zipfile

    zpath = tmp_path / "bundle.zip"
    with zipfile.ZipFile(zpath, "w") as zf:
        zf.write(_FIXTURES / "bundle_full_pass.json", "bundle.json")

    result = verify_bundle_file(zpath)
    assert result.verdict == "PASS"


def test_tampered_byte_fails():
    result = verify_bundle_file(_FIXTURES / "bundle_tampered.json")
    assert result.verdict == "FAIL"
    step = next(s for s in result.step_results if s.check == "payload_hash_integrity")
    assert step.result == "FAIL"


def test_chain_break_fails():
    result = verify_bundle_file(_FIXTURES / "bundle_chain_break.json")
    assert result.verdict == "FAIL"
    step = next(s for s in result.step_results if s.check == "chain_continuity")
    assert step.result == "FAIL"


def test_countersig_forged_signature_fails(tmp_path):
    bundle = json.loads((_FIXTURES / "bundle.json").read_text())
    bundle["countersignatures"][0]["signature"] = bundle["countersignatures"][1]["signature"]
    path = tmp_path / "forged.json"
    path.write_text(json.dumps(bundle))

    result = verify_bundle_file(path)
    assert result.verdict == "FAIL"
    step = next(s for s in result.step_results if s.check == "ed25519_countersig")
    assert step.result == "FAIL"


def test_missing_key_material_reports_hmac_unverifiable():
    result = verify_bundle_file(_FIXTURES / "bundle.json")
    step = next(s for s in result.step_results if s.check == "hmac_verify")
    assert step.result == "UNVERIFIABLE"


def test_missing_bundle_path_raises(tmp_path):
    from sengol_verify.bundle import BundleFormatError, load_bundle

    with pytest.raises(BundleFormatError):
        load_bundle(tmp_path / "does_not_exist.json")


def test_directory_with_wrong_number_of_json_files_raises(tmp_path):
    from sengol_verify.bundle import BundleFormatError, load_bundle

    (tmp_path / "a.json").write_text("{}")
    (tmp_path / "b.json").write_text("{}")

    with pytest.raises(BundleFormatError):
        load_bundle(tmp_path)


def test_record_with_no_canonical_form_fails_instead_of_raising(tmp_path):
    """An integer beyond 2**53 has no RFC 8785 form, so no signer produced
    the record as it stands: the verdict is FAIL, not a traceback."""
    bundle = json.loads((_FIXTURES / "bundle.json").read_text())
    bundle["records"][0]["sequence_number_extra"] = 2**60
    path = tmp_path / "unencodable.json"
    path.write_text(json.dumps(bundle))

    result = verify_bundle_file(path)
    assert result.verdict == "FAIL"
    step = next(s for s in result.step_results if s.check == "payload_hash_integrity")
    assert step.result == "FAIL"
    assert bundle["records"][0]["record_id"] in step.detail


def test_erased_or_edited_reason_text_leaves_a_genuine_bundle_passing(tmp_path):
    """The text is not signed (sengol ADR-0078): an erasure serves it empty
    with a status, and the signed `reason_digest` stays in the bytes. This
    tool holds no install key, so it cannot check the text itself."""
    bundle = json.loads((_FIXTURES / "bundle_full_pass.json").read_text())
    score = bundle["records"][0]["eval_result"]["scores"][0]
    assert score["reason_digest"].startswith("hmac-sha256:")
    score["reason"] = ""
    score["reason_status"] = "ERASED"
    bundle["records"][1]["eval_result"]["scores"][0]["reason"] = "edited after signing"
    path = tmp_path / "erased.json"
    path.write_text(json.dumps(bundle))

    result = verify_bundle_file(path)
    assert result.verdict == "PASS", [(s.check, s.result, s.detail) for s in result.step_results]


def test_tampered_reason_digest_fails(tmp_path):
    bundle = json.loads((_FIXTURES / "bundle_full_pass.json").read_text())
    bundle["records"][1]["eval_result"]["scores"][0]["reason_digest"] = "hmac-sha256:" + "0" * 64
    path = tmp_path / "digest.json"
    path.write_text(json.dumps(bundle))

    result = verify_bundle_file(path)
    assert result.verdict == "FAIL"
    step = next(s for s in result.step_results if s.check == "payload_hash_integrity")
    assert step.result == "FAIL"
